// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/joaolima7/cloud_run-goexpert/config"
	"github.com/joaolima7/cloud_run-goexpert/internal/domain/cep/repository"
	"github.com/joaolima7/cloud_run-goexpert/internal/domain/cep/usecase"
	"github.com/joaolima7/cloud_run-goexpert/internal/infra/external/cep"
	"github.com/joaolima7/cloud_run-goexpert/internal/infra/http_client"
	"time"
)

// Injectors from wire.go:

func InitializeGetCityByCepUseCase() (*usecase.GetCityByCepUseCase, error) {
	httpClient := provideHTTPClient()
	getCityByCepRepository := provideCepRepository(httpClient)
	getCityByCepUseCase := provideGetCityUseCase(getCityByCepRepository)
	return getCityByCepUseCase, nil
}

// wire.go:

func provideConfig() (*config.Config, error) {
	return config.LoadConfig()
}

func provideHTTPClient() httpclient.HTTPClient {
	return httpclient.NewHTTPClientImpl(10 * time.Second)
}

func provideCepRepository(client httpclient.HTTPClient) repository.GetCityByCepRepository {
	return cep.NewGetCityByCepRepositoryImpl(client)
}

func provideGetCityUseCase(repo repository.GetCityByCepRepository) *usecase.GetCityByCepUseCase {
	return usecase.NewGetCityByCepUseCase(repo)
}

var (
	configSet = wire.NewSet(provideConfig)
	clientSet = wire.NewSet(provideHTTPClient)

	repoSet = wire.NewSet(
		clientSet,
		provideCepRepository,
	)

	getCityUseCaseSet = wire.NewSet(
		repoSet,
		provideGetCityUseCase,
	)
)
